version: '3.8' #実行時点での最新バージョン
services:
  web:
    build:
      context: . #sampleディレクトリ
      dockerfile: docker/rails/Dockerfile 
    command: /bin/sh -c "rm -f /myproject/tmp/pids/server.pid && bundle exec unicorn -c /myproject/config/unicorn.conf.rb -D -E production"
    volumes:
      - .:/myproject #ホストのRailsアプリをバインドマウントする。
      - tmp-data:/myproject/tmp/sockets #ソケット通信用ファイルをnginxコンテナと共有
      - public-data:/myproject/public #publicデータをnginxと共有  
    tty: true
    stdin_open: true 

  nginx:
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always #明示的にstopさせるまでリスタートする。（失敗するたび遅延あり）
    volumes:
      - tmp-data:/myproject/tmp/sockets
      - public-data:/myproject/public
    depends_on:
      - web 

volumes:
  public-data:
  tmp-data: