default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: sky_development

test:
  <<: *default
  database: sky_test

production:
  <<: *default
  database: sky_production
  username: <%= Rails.application.credentials.dig(:maria,:username) %>
  password: <%= Rails.application.credentials.dig(:maria,:password) %>
  host: <%= Rails.application.credentials.dig(:maria,:host) %> 